# Generated by Django 4.1.3 on 2022-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('Ma', 'MASTER'), ('Tr', 'TRAVELER'), ('Us', 'USER'), ('Bl', 'BLOGER'), ('Gu', 'GUIDE')], max_length=2),
        ),
    ]
