# Generated by Django 4.1.3 on 2022-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unicid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
