# Generated by Django 4.1.3 on 2022-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_customuser_unicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('Ma', 'MASTER'), ('Tr', 'TRAVELER'), ('Us', 'USER'), ('Bl', 'BLOGER'), ('Gu', 'GUIDE')], default='Us', max_length=2),
        ),
    ]
