# Generated by Django 4.1.3 on 2022-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_customuser_mobile_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
