# Generated by Django 4.1.3 on 2022-11-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_remove_transport_stars_transport_graid_star_and_more'),
        ('Account', '0007_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.city'),
        ),
    ]
