# Generated by Django 4.1.3 on 2022-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profesional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
