# Generated by Django 4.1.3 on 2022-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_frame_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimg',
            name='title',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='title',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
