# Generated by Django 4.1.3 on 2022-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_articleimg_title_articlelink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimg',
            name='image',
            field=models.ImageField(upload_to='Frame'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Frame'),
        ),
    ]
