# Generated by Django 4.1.3 on 2022-11-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exno', models.CharField(max_length=10)),
                ('remainingtime', models.DurationField()),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Ho', 'HOTEL'), ('Mo', 'MOTEL'), ('HA', 'HAUSE'), ('Su', 'SUIT')], max_length=2)),
                ('address', models.TextField()),
                ('telnum', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('userscore', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startcontract', models.DateTimeField()),
                ('endcontract', models.DateTimeField()),
                ('adultprice', models.PositiveIntegerField()),
                ('childprice', models.PositiveIntegerField()),
                ('babyprice', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('adultcapacity', models.PositiveIntegerField()),
                ('userscore', models.PositiveIntegerField(blank=True, null=True)),
                ('buyscore', models.PositiveIntegerField(blank=True, null=True)),
                ('extradition', models.ManyToManyField(related_name='ro_exno', to='Home.extradition')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bu', 'BUS'), ('Tr', 'TRAIN'), ('Pl', 'AIR_PLAN')], max_length=2)),
                ('terminalname', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.city')),
            ],
        ),
        migrations.CreateModel(
            name='TransportCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('telnum', models.CharField(blank=True, max_length=15, null=True)),
                ('userscore', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportCode', models.CharField(max_length=15)),
                ('starttime', models.DateTimeField()),
                ('recivetime', models.DateTimeField()),
                ('capacityadult', models.PositiveIntegerField()),
                ('adultprice', models.PositiveIntegerField(blank=True, null=True)),
                ('childprice', models.PositiveIntegerField(blank=True, null=True)),
                ('babyprice', models.PositiveIntegerField(blank=True, null=True)),
                ('stars', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('userscore', models.PositiveIntegerField(blank=True, null=True)),
                ('buyscore', models.PositiveIntegerField(blank=True, null=True)),
                ('beginning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning', to='Home.terminal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.transportco')),
                ('distinaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinaton', to='Home.terminal')),
                ('extradition', models.ManyToManyField(related_name='tr_exno', to='Home.extradition')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userscore', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('buyscore', models.PositiveIntegerField(blank=True, null=True)),
                ('extradition', models.ManyToManyField(related_name='to_exno', to='Home.extradition')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.room')),
                ('transportBack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_ba', to='Home.transport')),
                ('transportGo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_go', to='Home.transport')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.state'),
        ),
    ]
