# Generated by Django 4.1.2 on 2022-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_residence_capacity_room_capacity_tour_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phon_number', models.CharField(max_length=55)),
                ('facebook', models.CharField(default='#', max_length=100)),
                ('twiter', models.CharField(default='#', max_length=100)),
                ('linkedin', models.CharField(default='#', max_length=100)),
                ('insta', models.CharField(default='#', max_length=100)),
                ('utube', models.CharField(default='#', max_length=100)),
            ],
        ),
    ]
