# Generated by Django 4.1.2 on 2022-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_mycompanyinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='home_page_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Cities'),
        ),
        migrations.AddField(
            model_name='city',
            name='short_description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
