# Generated by Django 4.1.2 on 2022-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_city_home_page_display_city_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='short_description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
