# Generated by Django 4.1.3 on 2022-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_city_image_alter_city_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='home_page_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
