# Generated by Django 4.1.3 on 2022-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_tour_home_page_display_tour_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Tour'),
        ),
    ]
