# Generated by Django 4.1.3 on 2022-11-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_room_adultcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.city'),
        ),
    ]
