# Generated by Django 4.1.3 on 2022-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_room_adultprice_currency_room_babyprice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='buyscore',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
