# Generated by Django 4.1.3 on 2022-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_rename_distinaton_transport_distination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='stars',
        ),
        migrations.AddField(
            model_name='transport',
            name='graid_star',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='graid_star',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True),
        ),
    ]
