# Generated by Django 4.1.3 on 2022-12-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_comment'),
        ('Home', '0018_tour_detail_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='detail_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bookit', to='Blog.article'),
        ),
    ]
