# Generated by Django 4.1.3 on 2022-12-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_tour_detail_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='userscore',
        ),
    ]
