# Generated by Django 4.1.3 on 2022-12-11 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user_rel',
            name='traveler',
            field=models.ManyToManyField(related_name='uo_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='cart_User_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(related_name='cart_rel', to='Cart.cart')),
                ('traveler', models.ManyToManyField(related_name='uc_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
