# Generated by Django 4.1.3 on 2022-12-11 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0002_alter_order_user_rel_traveler_cart_user_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_user_rel',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_user_rel',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='order_user_rel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_user_rel',
            name='traveler',
        ),
        migrations.AddField(
            model_name='cart_user_rel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_rel', to='Cart.cart'),
        ),
        migrations.AddField(
            model_name='cart_user_rel',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uc_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_user_rel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_rel', to='Cart.order'),
        ),
        migrations.AddField(
            model_name='order_user_rel',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uo_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
